### ISSUE TITLE
Unable to use buttons in the mouse example

### ISSUE THREAD

**Issue by vigneshjathavara** [unbit/foohid#6]
Im setting mouse.buttons = 4; that should work by pressing left button of the mouse. but nothing happens. The navigation using x and y is working properly but button clicks are not

**Comment by vigneshjathavara** [comment]
Actually it works but i think the 3 bits used are centerClick, RightClick, LeftClick

**Comment by aldur** [comment]
If I stand correctly you have to issue 2 separate events in order for the click to be detected (press & release.
For what regards the clicks: `0x01` is left, `0x02` is right and `0x04` is middle, so what you say it's correct.

Let me know if you need other info.

**Comment by vigneshjathavara** [comment]
Yes it works!! Thanks a lot :)
